batch_size: 256
num_workers: 4
pin_memory: true
task: EW_vs_Background
n_features: 32
hidden_width: 128
n_hidden_layers: 4
dropout_rate: 0.3
init_var_scale: 2.952
init_bias_std: 0.2
learning_rate: 0.001
adam_eps: 1.0e-08
weight_strategy: process
max_epochs: 200
early_stopping_patience: 10
early_stopping_threshold: 0
parquet_dir: Sample/Parquet/batch_sr_parquet_mg_sample
output_dir: ./DNN/results/ew_vs_bg
seed: 42