batch_size: 512
num_workers: 4
pin_memory: true
task: PolState_LL_LT_vs_TT
model_structure: ParT_Light
num_channels: 5
use_met: true
clean_duplicates: true
pt_log_scale: true
learning_rate: 0.001
weight_strategy: hybrid
balance_signal_background_weights: true
max_epochs: 200
early_stopping_patience: 10
early_stopping_threshold: 0
parquet_dir: Sample/Parquet/batch_refined_constituent_parquet_mg_sample
output_dir: ./ParT/results/ll_lt_vs_tt_refined_5ch_met
seed: 42
max_particles: 128
